name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cache: [0, 1]

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          DOCKER_BUILDKIT=${{ matrix.cache }} COMPOSE_DOCKER_CLI_BUILD=${{ matrix.cache }} docker-compose up
