name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          docker-compose up
